-- MySQL Script generated by MySQL Workbench
-- Tue Sep 15 17:03:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_SCAR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_SCAR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_SCAR` DEFAULT CHARACTER SET utf8 ;
USE `BD_SCAR` ;

-- -----------------------------------------------------
-- Table `BD_SCAR`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`ROLES` (
  `rol_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental del rol',
  `rol_nombre` VARCHAR(50) NOT NULL COMMENT 'Nombre del perfil de acceso',
  PRIMARY KEY (`rol_id`),
  UNIQUE INDEX `rol_nombre_UNIQUE` (`rol_nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`CATEGORIAS` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental de la categoría',
  `categoria_nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre de la clasificación (sabores, peso, etc)',
  PRIMARY KEY (`categoria_id`),
  UNIQUE INDEX `categoria_nombre_UNIQUE` (`categoria_nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`PRODUCTOS` (
  `producto_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental del producto',
  `producto_codigo` VARCHAR(50) NOT NULL COMMENT 'Código alfanumérico único (SKU) de inventario (ej. DUL-QC-001)',
  `producto_nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre comercial del dulce o producto',
  `producto_descripción` VARCHAR(225) NULL COMMENT 'Detalles de ingredientes, presentación y características del producto',
  `producto_precio` DECIMAL(10,2) NOT NULL COMMENT 'Precio de venta unitario en pesos colombianos ($ COP)',
  `producto_stock` INT NOT NULL COMMENT 'Cantidad de unidades físicas disponibles en inventario',
  `producto_peso` DECIMAL(8,2) NULL COMMENT 'Peso neto del producto expresado en gramos',
  `producto_imagen` VARCHAR(225) NULL COMMENT 'Ruta de archivo o URL de la imagen del producto',
  `producto_estado` VARCHAR(20) NOT NULL COMMENT 'Disponibilidad comercial del ítem (Disponible/agotado)',
  `CATEGORIAS_categoria_id` INT NOT NULL COMMENT 'Llave foránea que referencia la categoría asociada en CATEGORIAS',
  PRIMARY KEY (`producto_id`),
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`CATEGORIAS_categoria_id` ASC) ,
  UNIQUE INDEX `producto_codigo_UNIQUE` (`producto_codigo` ASC) ,
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_categoria_id`)
    REFERENCES `BD_SCAR`.`CATEGORIAS` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`REPARTIDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`REPARTIDORES` (
  `repartidor_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental del repartidor',
  `repartidor_nombre` VARCHAR(100) NOT NULL COMMENT 'Nombre completo del repartidor o domiciliario',
  `repartidor_telefono` VARCHAR(20) NOT NULL COMMENT 'Número de teléfono celular para contacto y coordinación',
  `repartidor_estado` VARCHAR(20) NOT NULL COMMENT 'Disponibilidad laboral del domiciliario (DISPONIBLE, EN\\_RUTA, INACTIVO)',
  PRIMARY KEY (`repartidor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`USUARIOS` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental del usuario',
  `usuario_nombre` VARCHAR(100) NOT NULL COMMENT 'Nombres completos del usuario',
  `usuario_apellido` VARCHAR(100) NOT NULL COMMENT 'Apellidos completos del usuario',
  `usuario_cedula` VARCHAR(20) NOT NULL COMMENT 'Número de documento de identidad del usuario',
  `usuario_correo` VARCHAR(100) NOT NULL COMMENT 'Correo electrónico para autenticación e inicio de sesión',
  `usuario_telefono` VARCHAR(20) NOT NULL COMMENT 'Número telefónico de contacto principal',
  `usuario_direccion` VARCHAR(150) NOT NULL COMMENT 'Dirección de residencia o entrega del usuario',
  `usuario_contraseña` VARCHAR(225) NOT NULL COMMENT 'Clave de acceso encriptada para seguridad',
  `usuario_estado` VARCHAR(20) NOT NULL COMMENT 'Estado de la cuenta en la plataforma (activo/inactivo)',
  `ROLES_rol_id` INT NOT NULL COMMENT 'Llave foránea que referencia al rol asignado en la tabla ROLES',
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_USUARIOS_ROLES_idx` (`ROLES_rol_id` ASC) ,
  UNIQUE INDEX `usuario_cedula_UNIQUE` (`usuario_cedula` ASC) ,
  UNIQUE INDEX `usuario_correo_UNIQUE` (`usuario_correo` ASC) ,
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`ROLES_rol_id`)
    REFERENCES `BD_SCAR`.`ROLES` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`VENTAS` (
  `venta_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental de la transacción de venta',
  `venta_fecha` DATETIME NOT NULL COMMENT 'Fecha y hora exacta de realización del pedido',
  `venta_metodo_pago` VARCHAR(50) NOT NULL COMMENT 'Forma de pago eleccionada (efectivo, Nequi)',
  `venta_total` DECIMAL(10,2) NOT NULL COMMENT 'Monto total consolidado de la venta en COP',
  `venta_estado` VARCHAR(20) NOT NULL COMMENT 'Estado del ciclo del pedido (Pedido, confirmado, entregado, cancelado)',
  `USUARIOS_usuario_id` INT NOT NULL COMMENT 'Llave foránea del cliente que realizó la compara en USUARIOS',
  PRIMARY KEY (`venta_id`),
  INDEX `fk_VENTAS_USUARIOS1_idx` (`USUARIOS_usuario_id` ASC) ,
  CONSTRAINT `fk_VENTAS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_usuario_id`)
    REFERENCES `BD_SCAR`.`USUARIOS` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`DETALLE DE VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`DETALLE DE VENTAS` (
  `detalle_cantidad` INT NOT NULL COMMENT 'Cantidad de unidades vendidas del producto',
  `detalle_precio_historico` DECIMAL(10,2) NOT NULL COMMENT 'Precio unitario congelado al momento exacto de la compra',
  `detalle_subtotal` DECIMAL(10,2) NOT NULL COMMENT 'Valor total del reglón (cantidad x precio histórico)',
  `VENTAS_venta_id` INT NOT NULL COMMENT 'Llave foránea e identificadora de la venta asociada',
  `PRODUCTOS_producto_id` INT NOT NULL COMMENT 'Lave foránea identificadora del producto comprado',
  PRIMARY KEY (`VENTAS_venta_id`, `PRODUCTOS_producto_id`),
  INDEX `fk_DETALLE DE VENTAS_VENTAS1_idx` (`VENTAS_venta_id` ASC) ,
  INDEX `fk_DETALLE DE VENTAS_PRODUCTOS1_idx` (`PRODUCTOS_producto_id` ASC) ,
  CONSTRAINT `fk_DETALLE DE VENTAS_VENTAS1`
    FOREIGN KEY (`VENTAS_venta_id`)
    REFERENCES `BD_SCAR`.`VENTAS` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE DE VENTAS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_producto_id`)
    REFERENCES `BD_SCAR`.`PRODUCTOS` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SCAR`.`DOMICILIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SCAR`.`DOMICILIOS` (
  `domicilio_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único autoincremental del servicio de entrega',
  `domicilio_direccion` VARCHAR(200) NOT NULL COMMENT 'Dirección de destino del pedido especificada por el cliente',
  `domicilio_costo_envio` DECIMAL(10,2) NOT NULL COMMENT 'Valor o tarifa calculada por el servicio de flete',
  `domicilio_estado` VARCHAR(20) NOT NULL COMMENT 'Valor o tarifa calculada por el servicio de flete',
  `VENTAS_venta_id` INT NOT NULL COMMENT 'Llave foránea vinculada a la venta correspondiente en VENTAS',
  `REPARTIDORES_editorial_id` INT NULL COMMENT 'Llave foránea opcional que asigna al repartidor en REPARTIDORES',
  PRIMARY KEY (`domicilio_id`),
  INDEX `fk_DOMICILIOS_VENTAS1_idx` (`VENTAS_venta_id` ASC) ,
  INDEX `fk_DOMICILIOS_REPARTIDORES1_idx` (`REPARTIDORES_editorial_id` ASC) ,
  UNIQUE INDEX `VENTAS_venta_id_UNIQUE` (`VENTAS_venta_id` ASC) ,
  CONSTRAINT `fk_DOMICILIOS_VENTAS1`
    FOREIGN KEY (`VENTAS_venta_id`)
    REFERENCES `BD_SCAR`.`VENTAS` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOMICILIOS_REPARTIDORES1`
    FOREIGN KEY (`REPARTIDORES_repartidor_id`)
    REFERENCES `BD_SCAR`.`REPARTIDORES` (`repartidor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
